# Generated by Django 5.0.2 on 2024-03-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Attendance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
