# Generated by Django 5.0.3 on 2024-03-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Attendance', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
